server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordering_system
    username: ordering_system
    password: xiaodaoshi10.
  data:
    redis:
      host: localhost
      port: 6379
      password: xiaodaoshi10.
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8